# Generated by Django 5.1.3 on 2024-11-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionInv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestion',
            old_name='title',
            new_name='Nom_du_produit',
        ),
        migrations.RenameField(
            model_name='gestion',
            old_name='quantite',
            new_name='Quantite_en_stock',
        ),
        migrations.RenameField(
            model_name='gestion',
            old_name='minimunquantity',
            new_name='Seuil_minimun_en_stock',
        ),
        migrations.RenameField(
            model_name='gestion',
            old_name='type',
            new_name='Type_de_produit',
        ),
        migrations.RenameField(
            model_name='gestion',
            old_name='description',
            new_name='description_du_produit',
        ),
    ]
